# Generated by Django 3.1.7 on 2021-03-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fingerprint',
        ),
    ]
